### PR TITLE
JustAnOkapi Merge - Semantic implementation

### PR DESCRIPTION
**Pull request by JustAnOkapi**
@Lin2Jing4 
* Fix meta tags
* Semantic framework implementation
-- header
-- loading placeholder
-- autohide with no content
* Add Examples to menu
* Clean menu ui

image_2020-12-18_231436

### CODE REVIEW

**Review by Lin2Jing4 — CHANGES_REQUESTED** [review]
- The [mobile](https://developers.google.com/web/tools/chrome-devtools/device-mode) accessibility is not [friendly](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/Mobile#Specific_mobile_considerations) enough.

firefox_RUwkPTDqO3

**Comment by Lin2Jing4** [comment]
- I have created an improved layout [here](https://github.com/Lin2Jing4/WolfreeAlpha.github.io) with [demo](https://lin2jing4.github.io/WolfreeAlpha.github.io/).

firefox_QVTdAeWaSn

firefox_bVCrKgUdLS

**Comment by JustAnOkapi** [comment]
I was working on that right now!
I will push my commits when it's ready.

**Comment by Lin2Jing4** [comment]
- Consider removing that `Show Step-by-Step Solutions` button.
  - Just as there is no "click to search" button on [google.com](https://www.google.com/).

- The [headerSmall_14ipXg3E.png](https://www.wolframalpha.com/_next/static/images/headerSmall_14ipXg3E.png) is superfluous and noniconic.
  - Consider removing it or replacing it with [CalabiYau5.jpg](https://zh.wikipedia.org/wiki/File:CalabiYau5.jpg).

- The statement 
  
  > Unlock/Receive FREE unlimited access to Wolfram|Alpha's full Step-by-step solutions.
  
  is mouthful and awkward. Something like
  
  > Get access to [Wolfram|Alpha](https://www.wolframalpha.com/) Pro features.
  > Unlock full [step-by-step](https://www.wolframalpha.com/examples/pro-features/step-by-step-solutions/) solutions for FREE.
  
  would sounds better.

**Comment by Lin2Jing4** [comment]
- Consider removing that `Show Step-by-Step Solutions` button. Just as there is no "click to search" button on [google.com](https://www.google.com/).
  
  
- The [headerSmall_14ipXg3E.png](https://www.wolframalpha.com/_next/static/images/headerSmall_14ipXg3E.png) is superfluous and noniconic. Consider removing it or replacing it with [CalabiYau5.jpg](https://zh.wikipedia.org/wiki/File:CalabiYau5.jpg).
  
  
- The statement 
  
  > Unlock/Receive FREE unlimited access to Wolfram|Alpha's full Step-by-step solutions.
  
  is mouthful and awkward. Something like
  
  > Get access to [Wolfram|Alpha](https://www.wolframalpha.com/) Pro features.
  > Unlock full [step-by-step](https://www.wolframalpha.com/examples/pro-features/step-by-step-solutions/) solutions for FREE.
  
  would sounds better.

**Comment by Lin2Jing4** [comment]
My layout ([demo](https://lin2jing4.github.io/WolfreeAlpha.github.io/)) is ready. **The [GitHub Pages site](https://wolfreealpha.github.io/) will be built from the [`lin2jing4/feature/front-end`](https://github.com/WolfreeAlpha/WolfreeAlpha.github.io/tree/lin2jing4/feature/front-end) branch if [`JustAnOkapi:main`](https://github.com/JustAnOkapi/WolfreeAlpha.github.io) is still in progress by Christmas Eve.** No worries. We don't live by timetables. Take everything at your own pace.

**Comment by Lin2Jing4** [comment]
I convert the pull request to a draft to indicate further changes are needed.
Mark your draft pull request as ready for review after addressing the mobile accessibility.

**Comment by Lin2Jing4** [comment]
Hey @JustAnOkapi, we haven't heard from you for a while. We hope you're doing fine. Should you have questions or queries, comment under this ticket, and we'd be pleased to answer.

Closing the ticket is only a formal and operational to ask, then if you like, you can get in touch again with us using the various communication channels.

Don't worry, though. We understand that there can be circumstances due to which you are unable to devote time. But you can come back later too and continue contributing from wherever you left off.

**Comment by Lin2Jing4** [comment]
Hey @JustAnOkapi, we haven't heard from you for a while. We hope you're doing fine. Should you have questions or queries, comment under this ticket, and we'd be pleased to answer.

Closing the ticket is only a formal and operational to ask, then if you like, you can get in touch again with us using the various communication channels.

Don't worry, though. We understand that there can be circumstances due to which you are unable to devote time. But you can come back later too and continue contributing from wherever you left off.

**Comment by JustAnOkapi** [comment]
I originally started this when I had a bit of extra and wanted to help out on a site that I liked. Maybe in a week I can have another go at this if you wanted.

**Comment by Lin2Jing4** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/6945
Although Semantic-UI is not strictly deprecated, I would recommend switching to [Material-UI](https://github.com/mui-org/material-ui).

**Comment by Lin2Jing4** [comment]
I spent some time researching the [popular frameworks](https://github.com/troxler/awesome-css-frameworks) and found that Semantic-UI is [no longer maintained](https://github.com/Semantic-Org/Semantic-UI/commits/master). Material-UI is a plausible alternative. After all, with all the spaghetti I've written so far, I'll need to rewrite the entire codebase with React sooner or later.

**Pull request closed without merging**
