### PR TITLE
Improved UI design

### PR DESCRIPTION
**Pull request by BrianKo14**
Basically, I tried to make it prettier. I used the original color codes from WolframAlpha.

### CODE REVIEW

**Comment by Lin2Jing4** [comment]
Deploy Preview #36
https://deploy-preview-36--wolfreealpha.netlify.app/

**Comment by Lin2Jing4** [comment]
This pull request will likely not be merged, as it only alters the user interface. It neither introduces new features to the product nor improves the maintainability of the codebase.

**Comment by Lin2Jing4** [comment]
Not for the [first time](https://github.com/WolfreeAlpha/WolfreeAlpha.github.io/pull/10), contributors are wasting their efforts. Ideally, I will explain in a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file how they can get a better indication of what would or would not be accepted before they begin the work.

**Comment by Lin2Jing4** [comment]
Some successful PRs involving UI changes are https://github.com/Animenosekai/freeWolframAlpha/pull/2 to bring new features and #34 to enhance maintainability.

**Comment by BrianKo14** [comment]
Well, it does look ugly. I was just trying to help

**Pull request closed without merging**
